{
 "title": "Breweries Monitornig",
 "time": { "from": "2025-02-05T08:04:20.290Z", "to": "2025-02-13T08:04:20.290Z" },
 "panels": [
  {
   "title": "last executions status",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \ndag_id,\nexecution_date,\nstate\nFROM dag_run a\nwhere execution_date = (SELECT exec_date from (SELECT dag_id, max(execution_date) exec_date from dag_run b where a.dag_id = b.dag_id GROUP BY dag_id)c ) \norder by execution_date DESC"
    }
   ]
  },
  {
   "title": "DAGs Executions number",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT execution_date, COUNT(id) fail FROM dag_run where state = 'failed' GROUP BY execution_date LIMIT 50 "
    },
    {
     "rawSql": "SELECT execution_date, COUNT(id) success FROM dag_run where state = 'success' group BY execution_date"
    }
   ]
  },
  {
   "title": "Available DAGs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \ndag_id,\nis_active,\nowners,\nlast_parsed_time\nFROM dag LIMIT 50 "
    }
   ]
  }
 ]
}